import { Link } from "wouter";
import { AlertTriangle, ArrowUpRight, CloudRain, Droplets, Gauge, MapPinned, Plus, RadioTower, RefreshCw, ShieldAlert, Waves } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useApp } from "../contexts/AppContext";
import { riskTone, moistureBand, formatDate } from "../lib/risk";

function StatCard({ label, value, note, icon: Icon, tone }: { label: string; value: string | number; note: string; icon: typeof Gauge; tone: string }) {
  return <div className="card-surface flex min-h-[150px] flex-col justify-between p-5"><div className="flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-2xl ${tone}`}><Icon size={19} /></span><ArrowUpRight size={17} className="text-[#9aac9f]" /></div><div><p className="font-display text-3xl tracking-[-0.05em]">{value}</p><div className="mt-1 flex items-center justify-between gap-3"><p className="text-xs font-bold tracking-[0.13em] text-[#718279] uppercase">{label}</p><span className="text-[11px] text-[#89978f]">{note}</span></div></div></div>;
}

export default function Dashboard() {
  const { locations, reports, alerts, readings, loading, error, refresh } = useApp();
  const high = locations.filter((l) => l.risk_level === "High").length;
  const medium = locations.filter((l) => l.risk_level === "Medium").length;
  const low = locations.filter((l) => l.risk_level === "Low").length;
  const chartData = locations.map((l) => ({ name: l.name, rainfall: l.rainfall_mm, risk: l.risk_level }));
  const latestAlerts = alerts.slice(0, 3);

  if (loading && !locations.length) return <div className="grid min-h-[60vh] place-items-center"><div className="text-center"><RefreshCw className="mx-auto mb-3 animate-spin text-[#527361]" /><p className="text-sm text-[#718279]">Loading monitoring workspace…</p></div></div>;
  if (error) return <div className="card-surface mx-auto max-w-2xl p-8 text-center"><ShieldAlert className="mx-auto mb-4 text-[#c74335]" size={28} /><h2 className="font-display text-2xl">Supabase setup needed</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#718279]">{error}</p><button onClick={refresh} className="button-primary mx-auto mt-5"><RefreshCw size={16} /> Retry connection</button></div>;

  return <div className="space-y-8">
    <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Tuesday · 08 September 2026</p><h2 className="page-title">Good morning, operator.</h2><p className="page-subtitle">A clear read on the terrain signals that need your attention today.</p></div><div className="flex gap-3"><Link href="/report" className="button-primary"><Plus size={17} /> New field report</Link><Link href="/map" className="button-secondary"><MapPinned size={17} /> Open risk map</Link></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="High risk zones" value={high} note="Needs review" icon={ShieldAlert} tone="bg-[#fff0ed] text-[#c74335]" /><StatCard label="Medium risk zones" value={medium} note="Watch closely" icon={Waves} tone="bg-[#fff8e9] text-[#a06c14]" /><StatCard label="Stable zones" value={low} note="Lower signal" icon={Gauge} tone="bg-[#eef8f2] text-[#24784f]" /><StatCard label="Field reports" value={reports.length} note="All submissions" icon={RadioTower} tone="bg-[#edf3fb] text-[#3e6f9e]" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.55fr_0.95fr]">
      <div className="card-surface p-5 sm:p-7"><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Rainfall signal</p><h3 className="section-title">Rainfall vs. risk zones</h3></div><div className="rounded-xl bg-[#edf3ea] px-3 py-2 text-xs font-bold text-[#527361]">mm / location</div></div><div className="h-[260px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{ top: 5, right: 0, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e6ece5" /><XAxis dataKey="name" tick={{ fill: "#819087", fontSize: 10 }} tickLine={false} axisLine={false} interval={0} angle={-32} textAnchor="end" height={60} /><YAxis tick={{ fill: "#819087", fontSize: 10 }} tickLine={false} axisLine={false} /><Tooltip cursor={{ fill: "#f1f5ef" }} contentStyle={{ borderRadius: 14, border: "1px solid #dce5dd", boxShadow: "0 12px 30px rgba(32,49,43,.08)" }} formatter={(value, _name, item) => [`${value} mm`, `${item.payload.risk} risk`]} /><Bar dataKey="rainfall" radius={[7, 7, 2, 2]} fill="#7da88b" /></BarChart></ResponsiveContainer></div></div>
      <div className="card-surface p-5 sm:p-7"><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Attention queue</p><h3 className="section-title">Latest alerts</h3></div><Link href="/admin" className="text-xs font-bold text-[#527361]">View all</Link></div><div className="space-y-4">{latestAlerts.length ? latestAlerts.map((alert) => <div key={alert.id} className="flex gap-3 border-b border-[#edf0eb] pb-4 last:border-0 last:pb-0"><span className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-xl ${alert.severity === "High" || alert.severity === "Critical" ? "bg-[#fff0ed] text-[#c74335]" : "bg-[#fff8e9] text-[#a06c14]"}`}><AlertTriangle size={15} /></span><div className="min-w-0"><p className="truncate text-sm font-bold">{alert.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#718279]">{alert.message}</p><p className="mt-2 text-[10px] font-bold tracking-[0.1em] text-[#a2aea6] uppercase">{formatDate(alert.created_at)}</p></div></div>) : <div className="rounded-2xl bg-[#f7faf6] p-5 text-sm text-[#718279]">No alerts yet. Create one from a high-signal location.</div>}</div></div>
    </section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><div className="card-surface p-5 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><p className="eyebrow">Risk method</p><h3 className="section-title">How this workspace calculates risk</h3></div><span className="rounded-full bg-[#173c34] px-3 py-1 text-[10px] font-bold tracking-[0.12em] text-[#d9ee74] uppercase">Rule engine</span></div><div className="grid gap-3 sm:grid-cols-2"><div className="signal-card"><span className="signal-number">01</span><div><strong>Rainfall</strong><p>High at 100 mm or more.</p></div></div><div className="signal-card"><span className="signal-number">02</span><div><strong>Slope angle</strong><p>High at 30° or more.</p></div></div><div className="signal-card"><span className="signal-number">03</span><div><strong>Soil moisture</strong><p>Saturated at 70% or more.</p></div></div><div className="signal-card"><span className="signal-number">04</span><div><strong>Past landslide</strong><p>Historical event adds a signal.</p></div></div></div><p className="mt-5 border-t border-[#edf0eb] pt-4 text-xs leading-5 text-[#839188]">High risk is triggered by combined rainfall and slope, prior landslide with heavy rain, or saturated soil with heavy rain. Values update when an operator edits a location or adds a sensor reading.</p></div><div className="card-surface overflow-hidden p-5 sm:p-7"><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Moisture watch</p><h3 className="section-title">Latest sensor readings</h3></div><Link href="/sensors" className="rounded-xl bg-[#edf3ea] p-2 text-[#527361]"><ArrowUpRight size={16} /></Link></div><div className="space-y-3">{(readings.length ? readings.slice(0, 4) : locations.slice(0, 4).map((l) => ({ id: l.id, location_id: l.id, moisture_pct: l.soil_moisture_pct, source: "Seeded location", recorded_at: l.updated_at || new Date().toISOString() }))).map((reading) => { const location = locations.find((l) => l.id === reading.location_id); const band = moistureBand(reading.moisture_pct); return <div key={reading.id} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#edf3ea] text-[#527361]"><Droplets size={15} /></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3 text-xs font-bold"><span className="truncate">{location?.name}</span><span className={band.text}>{reading.moisture_pct}%</span></div><div className={`mt-2 h-1.5 overflow-hidden rounded-full ${band.track}`}><div className="h-full rounded-full" style={{ width: `${reading.moisture_pct}%`, background: band.color }} /></div></div></div>; })}</div></div></section>
  </div>;
}
