import { useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowLeft, ClipboardCheck, Send } from "lucide-react";
import { toast } from "sonner";
import { useApp } from "../contexts/AppContext";
import { reportTypes, severities } from "../data/mockData";

export default function Report() {
  const [, navigate] = useLocation();
  const { locations, user, submitReport } = useApp();
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ reporter_name: user?.user_metadata?.full_name || "", phone: "", location_id: locations[0]?.id || "", report_type: reportTypes[0], severity: "Medium", description: "", observed_at: new Date().toISOString().slice(0, 16) });
  function update(key: string, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function handleSubmit(event: React.FormEvent) { event.preventDefault(); if (form.description.trim().length < 12) { toast.error("Add at least 12 characters describing what you observed."); return; } setBusy(true); try { await submitReport({ ...form, observed_at: new Date(form.observed_at).toISOString() }); toast.success("Field report saved to Supabase."); navigate("/admin"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save the report."); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-4xl space-y-7"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#527361]"><ArrowLeft size={16} /> Back to overview</Link><section><p className="eyebrow">Shared operations log</p><h2 className="page-title">Submit a field report</h2><p className="page-subtitle">Capture an observation once, then make it available to the whole monitoring team.</p></section><form onSubmit={handleSubmit} className="card-surface p-6 sm:p-8"><div className="mb-8 flex items-start gap-3 rounded-2xl bg-[#edf3ea] p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#d9ee74] text-[#173c34]"><ClipboardCheck size={17} /></span><div><p className="text-sm font-bold">Reports are shared records</p><p className="mt-1 text-xs leading-5 text-[#718279]">Your authenticated account is stored with the submission so the monitoring team can follow up.</p></div></div><div className="grid gap-5 sm:grid-cols-2"><label><span className="form-label">Reporter name</span><input className="field" value={form.reporter_name} onChange={(e) => update("reporter_name", e.target.value)} required placeholder="Full name" /></label><label><span className="form-label">Phone <em>optional</em></span><input className="field" value={form.phone} onChange={(e) => update("phone", e.target.value)} placeholder="+91 98765 43210" /></label><label><span className="form-label">Location</span><select className="field" value={form.location_id} onChange={(e) => update("location_id", e.target.value)} required>{locations.map((location) => <option key={location.id} value={location.id}>{location.name} · {location.state}</option>)}</select></label><label><span className="form-label">Observed at</span><input className="field" type="datetime-local" value={form.observed_at} onChange={(e) => update("observed_at", e.target.value)} required /></label><label><span className="form-label">Report type</span><select className="field" value={form.report_type} onChange={(e) => update("report_type", e.target.value)}>{reportTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label><span className="form-label">Severity</span><select className="field" value={form.severity} onChange={(e) => update("severity", e.target.value)}>{severities.map((severity) => <option key={severity}>{severity}</option>)}</select></label><label className="sm:col-span-2"><span className="form-label">What did you observe?</span><textarea className="field min-h-[150px] resize-y" value={form.description} onChange={(e) => update("description", e.target.value)} required minLength={12} placeholder="Describe cracks, debris, water flow, road access, or other relevant details…" /></label></div><div className="mt-7 flex justify-end"><button disabled={busy} className="button-primary"><Send size={17} /> {busy ? "Saving report…" : "Save field report"}</button></div></form></div>;
}
